### ISSUE TITLE
I have some git push problems with my codes.

### ISSUE THREAD

**Issue by byurudur** [byurudur/Patika-Projects#1]
How can I fix this code error?

**Comment by deerborg** [comment]
+1

**Comment by byurudur** [comment]
> +1

I have fixed the problem;

1. First open your git bash on your files
2. git fetch - git status - git push

**Comment by deerborg** [comment]
> > +1
> 
> I have fixed the problem;
> 
> 1. First open your git bash on your files
> 2. git fetch - git status - git push

Thx

**Comment by deerborg** [comment]
> > +1
> 
> I have fixed the problem;
> 
> 1. First open your git bash on your files
> 2. git fetch - git status - git push

opps not working

**Comment by byurudur** [comment]
> > > +1
> > 
> > 
> > I have fixed the problem;
> > 
> > 1. First open your git bash on your files
> > 2. git fetch - git status - git push
> 
> opps not working

Check out this issue on StackOverflow
